### ISSUE TITLE
Crashes when opening level.dat file

### ISSUE THREAD

**Issue by delsaranbigglesworth** [Podshot/MCEdit-Unified-Preview#17]
It says the repairwrapper does not match the C++ something. Would be nice to have a bug copy button on the error screen for quick copy. I feel like none of these are currently being worked on?

**Comment by Podshot** [comment]
Please re-submit this issue to the [actual MCEdit-Unified repository](https://github.com/Podshot/MCEdit-Unified) for us to take a look at it. Please follow. the given issue template.

For the bug copy request, we cannot add this functionality since the error is show through the console window, which doesn't support this.

We aren't working on the issues here because we are working on our new project [Amulet](https://www.amulet-editor.com/)  and since most of the issue do not pertain to actually launching the program. The second issue is outlined by the 4th bullet point in the Warnings section of the [README](https://github.com/Podshot/MCEdit-Unified-Preview#warnings)
