### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by freecode-ai** [Podshot/MCEdit-Unified-Preview#19]
I have been using this to edit my realms maps for Xbox One and I just want to say thanks. I am sure you are aware that some of the older blocks do not import properly but I just replace the old blocks with what it is supposed to be in creative on the Windows 10 edition, make the necessary changes, then export the new schematic for use on my survival world. Just wondering if it will be possible to actually edit the NBT player / item tags in the future? Currently nothing saves. Is this because that data isn't stored locally? Anyway, thanks for all of your hard work. I appreciate it.

**Comment by Podshot** [comment]
MCEdit-Unified is being phased out for the [Amulet Editor](https://www.amulet-editor.com/) due to the breaking changes in the level format introduced by Java 1.13+ and Bedrock 1.13+, and we plan for the new editor to support both Java and Bedrock in equal ability. I apologize if you were hoping that it would make it into MCEdit-Unified.

I also apologize for the lateness in my response, I've been pretty busy this week and didn't have a lot of time to keep track of new issues
